<!DOCTYPE story [
        <!ELEMENT story (step)*>
        <!ATTLIST story
            name CDATA #REQUIRED>
        <!ELEMENT step (nextStep|description|type|win)*>
        <!ATTLIST step
                id CDATA #REQUIRED
                title CDATA #REQUIRED>
        <!ELEMENT nextStep (#PCDATA)>
        <!ELEMENT description (#PCDATA)*>
        <!ELEMENT fragment (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT win (#PCDATA)>

        ]>
<story name="Want to win ?" >

    <step id="0" title="Welcome!">
        <nextStep>1</nextStep>
        <nextStep>2</nextStep>
        <description>First step !</description>
        <type>multiple_choice</type>
    </step>
    <step id="1" title="End! You loose">
        <description>Dead :(</description>
        <type>end</type>
        <win>false</win>
    </step>
    <step id="2" title="End! You win">
        <nextStep></nextStep>
        <description>win !</description>
        <type>end</type>
        <win>true</win>
    </step>
</story>
